export const STATUS_TYPES = {
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  PENDING: "PENDING",
};

export const ACTION_TYPES = {
  START: "START",
  CANCEL: "CANCEL",
  COMPLETE: "COMPLETE",
};

export const USER_TYPE = {
  ADMIN: "ADMIN",
  CUSTOMER: "CUSTOMER",
};
